export const SET_OWFC5DAYS = 'SET_OWFC5DAYS';
export const SET_OWFC16DAYS = 'SET_OWFC16DAYS';
export const SET_CITY = 'SET_CITY';
export const SET_SEARCH_CITY = 'SET_SEARCH_CITY';
export const SET_FETCH_STATUS = 'SET_FETCH_STATUS';
export const SET_WEATHERCHECK_LOCATIONS = 'SET_WEATHERCHECK_LOCATIONS';
export const SET_WEATHERCHECK_WEATHER = 'SET_WEATHERCHECK_WEATHER';
